/*  389 - Find the Difference - From @ LeetCode.com
    
    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Find the letter that was added in t.

    Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.

    Solution by @ Davis Ching, 2020.
 */
 
 class Solution {
    public char findTheDifference(String s, String t) {
        int[] cs = new int[26];
        for (char c : s.toCharArray())
            cs[c-'a'] += 1;
        for (char c : t.toCharArray())
            if (cs[c-'a']-- == 0)
                return c;
        return ' ';
    }
}
